version: '3.7'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9093:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"

  node_exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"

  custom_exporter:
    build: .
    restart: always
    ports:
      - "9101:9101"

volumes:
  grafana-storage:
